# Folders
DATA_DIR = "data"
CACHE_DIR = "cache"
OUTPUT_DIR = "output"

# Image size.
IMAGE_WIDTH = 1264
IMAGE_HEIGHT = 832

# Magic numbers.
NUMBER_OF_SPLATS_PER_PIXEL = 500
MINIMUM_TRANSMITTANCE = 0.001
